- name: Installing stow
  pacman: 
    name: stow
    state: present
  become: true
  tags: ['install', 'dotfiles', 'stow']

- name: cloning dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/7ze/dots'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
  tags: ['install', 'dotfiles', 'stow']

- name: stow dotfiles
  shell: cd $HOME/dotfiles && ./install.sh
  tags: ['install', 'dotfiles', 'stow']
