- name: Install zsh, starship
  pacman:
    name: ['zsh', 'starship']
    state: present
  tags: ['zsh', 'starship']
  become: true

- name: Set zsh as the default shell
  shell: chsh -s $(which zsh) zeus
  tags: ['zsh', 'starship']
  become: true
